### ISSUE TITLE
Groundwork city and postalcode

### ISSUE THREAD

**Issue by svanrintel** [Informatievlaanderen/GIPOD#178] opened 2020-10-30 13:13 UTC
In Gipod1 version we thought there where properties for city and postalcode of a groundwork (based on zone). Are they also available in Gipod²?

**Comment by sboden** [comment] 2020-11-01 14:13
This is a duplicate of [https://github.com/Informatievlaanderen/GIPOD/issues/161](https://github.com/Informatievlaanderen/GIPOD/issues/161)

**Comment by svanrintel** [comment] 2020-11-02 08:55
Will this also be available in the API call '/groundworks/ ?

**Comment by doomsju** [comment] 2020-11-02 10:31
API is fixed for the moment. Normally only bugfixes and stability improvements are allowed on the current version.

**Comment by AIV-Bert** [comment] 2020-12-10 18:28
For the current release this won't be available in the /groundworks API call.

If you want to search and filter on a specific City/Postalcode, the search endpoints support filtering on Niscode.

If you want to reverse geocode the zone, you can use this API: https://loc.geopunt.be

**Closed by AIV-Bert** 2020-12-10 18:28 UTC
Labels: bug
