### ISSUE TITLE
GIPOD BETA : Error when creating a new groundwork and not possible to open a GW

### ISSUE THREAD

**Issue by JoYsenbaardt** [Informatievlaanderen/GIPOD#307] opened 2022-01-19 09:28 UTC
When creating a new groundwork, an error message is shown "Fout, Er ging iets mis bij het laden".
We notice this problem only since today.

If you go to the lists of innames you see the GW has been created  (for example 10697167), but if you want to open this GW you get the same error message. You also can't open earlier created groundworks.

Can you solve this issue, because our test team is very impacted by this.

Thanks,
Jo

**Comment by AIV-Bert** [comment] 2022-01-19 10:05
Cannot reproduce for https://gipod.beta-vlaanderen.be/inname/10697167

Issue resolved in #306

**Closed by AIV-Bert** 2022-01-19 10:05 UTC
Labels: bug
